[package]
name = "citati"
version = "0.3.2"
edition = "2021"
authors = ["Jake W. Ireland <jakewilliami@icloud.com>"]

[dependencies]
biblatex = "0.10.0"
clap = { version = "4.5.20", features = ["cargo", "wrap_help", "derive"] }
lazy_static = "1.5.0"
regex = "1.11.0"
